pol = input()
if pol == "a1": print("black")  
elif pol == "a2": print("white")
elif pol == "a3": print("black")
elif pol == "a4": print("white")
elif pol == "a5": print("black")
elif pol == "a6": print("white")
elif pol == "a7": print("black")
elif pol == "a8": print("white")

elif pol == "b1": print("white")
elif pol == "b2": print("black")
elif pol == "b3": print("white")
elif pol == "b4": print("black")
elif pol == "b5": print("white")
elif pol == "b6": print("black")
elif pol == "b7": print("white")
elif pol == "b8": print("black")

elif pol == "c1": print("black")
elif pol == "c2": print("white")
elif pol == "c3": print("black")
elif pol == "c4": print("white")
elif pol == "c5": print("black")
elif pol == "c6": print("white")
elif pol == "c7": print("black")
elif pol == "c8": print("white")

elif pol == "d1": print("white")
elif pol == "d2": print("black")
elif pol == "d3": print("white")
elif pol == "d4": print("black")
elif pol == "d5": print("white")
elif pol == "d6": print("black")
elif pol == "d7": print("white")
elif pol == "d8": print("black")

elif pol == "e1": print("black")
elif pol == "e2": print("white")
elif pol == "e3": print("black")
elif pol == "e4": print("white")
elif pol == "e5": print("black")
elif pol == "e6": print("white")
elif pol == "e7": print("black")
elif pol == "e8": print("white")

elif pol == "f1": print("white")
elif pol == "f2": print("black")
elif pol == "f3": print("white")
elif pol == "f4": print("black")
elif pol == "f5": print("white")
elif pol == "f6": print("black")
elif pol == "f7": print("white")
elif pol == "f8": print("black")

elif pol == "g1": print("black")
elif pol == "g2": print("white")
elif pol == "g3": print("black")
elif pol == "g4": print("white")
elif pol == "g5": print("black")
elif pol == "g6": print("white")
elif pol == "g7": print("black")
elif pol == "g8": print("white")

elif pol == "h1": print("white")
elif pol == "h2": print("black")
elif pol == "h3": print("white")
elif pol == "h4": print("black")
elif pol == "h5": print("white")
elif pol == "h6": print("black")
elif pol == "h7": print("white")
elif pol == "h8": print("black")